### ISSUE TITLE
Mismatch Issue in VS 2015

### ISSUE THREAD

**Issue by facebookegypt** [dj-nitehawk/ThreadSafeAwesomium.Net#3]
I'm getting this warning 
Severity	Code	Description	Project	Project Rank	File	Line	Category	Source	Suppression State
Warning		There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "Awesomium.Windows.Forms, Version=1.7.5.1, Culture=neutral, PublicKeyToken=9bd24830fbe304a0, processorArchitecture=x86", "x86". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.	MyAccounts.vb	1				Build	

I've tried [AnyCpu] but still. 
Any idea how to overcome this ?

**Comment by dj-nitehawk** [comment]
awesomium has been long deprecated. so i'd advise you to use puppeteer instead:  https://www.puppeteersharp.com/examples/index.html
